# Generated by Django 3.1.5 on 2021-01-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.projects'),
        ),
    ]
