# Generated by Django 3.1.5 on 2021-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envs',
            name='id',
            field=models.AutoField(help_text='环境ID', primary_key=True, serialize=False, verbose_name='环境ID'),
        ),
    ]
