# Generated by Django 3.1.5 on 2021-01-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.AutoField(help_text='用例ID', primary_key=True, serialize=False, verbose_name='用例ID')),
                ('name', models.CharField(help_text='用例名称', max_length=200, unique=True, verbose_name='用例名称')),
                ('include', models.TextField(help_text='用例执行前置顺序', null=True, verbose_name='前置')),
                ('author', models.CharField(help_text='编写人员', max_length=50, verbose_name='编写人员')),
                ('request', models.TextField(help_text='请求信息', verbose_name='请求信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('interface', models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, to='interfaces.interfaces')),
            ],
            options={
                'verbose_name': '用例',
                'verbose_name_plural': '用例',
                'db_table': 'tb_testcases',
            },
        ),
    ]
