# Generated by Django 3.1.5 on 2021-01-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20210119_1515'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='include',
            field=models.TextField(help_text='用例执行前置顺序', null=True, verbose_name='用例执行前置顺序'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='interface',
            field=models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='interfaces.interfaces'),
        ),
    ]
